spring:
  rabbitmq:
    host: 10.66.0.2
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: test
        input:
          destination: test
